###############################################
# MediaMTX Configuration for NOMAD
# 
# Ultra-low latency configuration for FPV drone operations.
# Optimized for <150ms glass-to-glass latency.
#
# Source: https://github.com/bluenviron/mediamtx
###############################################

# ============================================================
# Global Settings - LOW LATENCY OPTIMIZED
# ============================================================

# Logging level (debug, info, warn, error)
logLevel: warn
logDestinations: [stdout]

# Minimal timeouts for low latency
readTimeout: 5s
writeTimeout: 5s
writeQueueSize: 64  # Smaller buffer = lower latency

# ============================================================
# API (for monitoring)
# ============================================================

api: yes
apiAddress: :9997
# Metrics for Prometheus
metrics: yes
metricsAddress: :9998

# ============================================================
# RTSP Server - LOW LATENCY OPTIMIZED
# ============================================================

rtsp: yes
rtspAddress: :8554
protocols: [udp, tcp]  # UDP first for lower latency

# Disable RTSP authentication for local/Tailscale access
rtspAuthMethods: []

# ============================================================
# RTMP Server (disabled)
# ============================================================

rtmp: no
rtmpAddress: :1935

# ============================================================
# HLS Server (disabled)
# ============================================================

hls: no
hlsAddress: :8888

# ============================================================
# WebRTC Server (disabled - using RTSP for Mission Planner)
# ============================================================

webrtc: no
webrtcAddress: :8889

# ============================================================
# SRT Server (disabled)
# ============================================================

srt: no
srtAddress: :8890

# ============================================================
# Recording (optional)
# ============================================================

record: no

# ============================================================
# Paths (stream endpoints) - ZED2i Multi-Camera Views
# ============================================================

paths:
  # ZED2i Stereo Stream
  # Full 2560x720 side-by-side stereo frame @ 30fps H.264
  # Mission Planner crops to Left/Right/Both views client-side
  zed:
    source: publisher
    # Allow anyone to publish
    publishUser:
    publishPass:

  # Alternative generic endpoint
  live:
    source: publisher
    publishUser:
    publishPass:

  # Test path for debugging
  test:
    source: publisher
    publishUser:
    publishPass:
